# Generated by Django 4.2.1 on 2023-06-13 08:01

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productOrder', models.ManyToManyField(to='academyCoffee.basket')),
            ],
        ),
    ]
