# Generated by Django 4.2.1 on 2023-06-10 19:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Номер телефона'),
        ),
    ]
