# Generated by Django 4.2.1 on 2023-06-08 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DateOfBirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='PNumber',
        ),
    ]
