# Generated by Django 4.2.1 on 2023-06-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0002_usercard_is_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='Наличные', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
