# Generated by Django 4.2.1 on 2023-06-11 14:34

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0002_alter_user_pnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
    ]
