# Generated by Django 4.2.1 on 2023-06-08 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0002_remove_user_dateofbirth_remove_user_pnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='DateOfBirth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='PNumber',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
