# Generated by Django 4.2.1 on 2023-06-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0003_order_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='user',
            name='payment_method',
            field=models.CharField(default='Наличные', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
