# Generated by Django 4.2.1 on 2023-06-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0003_remove_order_productorder_order_basket_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
