# Generated by Django 4.2.1 on 2023-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0004_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PNumber',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
