# Generated by Django 4.2.1 on 2023-06-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0005_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Промокод')),
                ('stock', models.PositiveSmallIntegerField(default=25, max_length=3)),
            ],
        ),
    ]
