# Generated by Django 4.2.1 on 2023-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0006_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Промокод'),
        ),
    ]
