# Generated by Django 4.2.1 on 2023-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0008_emailsubscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferForCooperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
                ('region', models.TextField(blank=True, choices=[('Красноярск', 'Красноярск'), ('Москва', 'Москва'), ('Санкт-Петерург', 'Санкт-Петерург'), ('Новосибирск', 'Новосибирск')], max_length=50, verbose_name='Регион')),
                ('text', models.TextField()),
                ('email', models.EmailField(max_length=50, verbose_name='Почта')),
            ],
        ),
    ]
