# Generated by Django 4.2.1 on 2023-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academyCoffee', '0009_offerforcooperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='stock',
            field=models.PositiveSmallIntegerField(default=25),
        ),
    ]
